### ISSUE TITLE
Deadlocking go blocks

### ISSUE THREAD

**Issue by halgari** [divs1210/functional-core-async#1]
This code appears to deadlock:

```
user=> (def c (chan))
#'user/c
user=> (go (println "got" (<! c)))
#object[java.util.concurrent.ArrayBlockingQueue 0x2e49f199 "[]"]
user=> (go (>! c 42) (println "sent"))
#object[java.util.concurrent.ArrayBlockingQueue 0x70cdcbe1 "[]"]
user=>

```

**Comment by divs1210** [comment]
Hi, @halgari! Thank you for pointing this out.

I think I understand now what you meant when you said it won't be possible to implement coroutines using functions - pre-emptive scheduling is problematic.

I have resolved this problem by modifying the scheduler to autopromote the `go` block into an actual JVM thread if the task doesn't complete within 10ms. This also unifies `go` and `thread` blocks as it makes the latter unnecessary.

Please let me know your thoughts on this. Closing this issue for now.

**Comment by divs1210** [comment]
Hi @halgari!
I have done a complete overhaul of the system.
I have implemented parking versions of `<!` and `>!`, but (because I'm not a sorcerer like you) they are rather simple and not as powerful as `core.async`'s versions.
This is what I had in mind when I said I wanted a more 'functional' implementation, but its drawbacks are pretty clear and now I understand what the original implementation must be doing.
Would love to hear from you!
